wandb_version: 1

train:
  desc: null
  value:
    num_workers: 0
    bsize: 512
    lr: 0.001
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.98
    warmup_steps: 10
    eval_every: 10
    eval_batches: 8
    max_steps: 1000000.0
wandb:
  desc: null
  value:
    use_wandb: true
    wandb_project: my_project
dataset:
  desc: null
  value: mod_subtract_dataset
model:
  desc: null
  value: grokk_model
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718121824
    t:
      1:
      - 1
      - 51
      - 55
      2:
      - 1
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
